apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  http://gitlab-webservice-default.gitlab.svc:8181/root/gitlab-argocd.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true