Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.hostname = "iouardiS"
	  config.vm.synced_folder "./config", "/vagrant", type:"virtualbox"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
	    vb.name = "iouardiS"
    end
    config.vm.provision "shell", path: "./scripts/p2Setup.sh"
end