Vagrant.configure("2") do |config|

  config.vm.define "iouardiS" do |vm1|
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.hostname = "iouardiS"
    vm1.vm.synced_folder "./config", "/vagrant", type:"virtualbox"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "iouardiS"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    vm1.vm.provision "shell", path: "./scripts/serverScript.sh"
  end
  
  config.vm.define "iouardiSW" do |vm2|
    vm2.vm.box = "bento/ubuntu-22.04"
    vm2.vm.network "private_network", ip: "192.168.56.111"
    vm2.vm.hostname = "iouardiSW"
    vm2.vm.synced_folder "./config", "/vagrant", type:"virtualbox"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "iouardiSW"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    vm2.vm.provision "shell", path: "./scripts/agentScript.sh"
  end
  
end