all:
	./scripts/setupBonus.sh

re: clean
	./scripts/setupBonus.sh

clean:
	./scripts/resetBonus.sh

details:
	./scripts/details.sh

install:
	./scripts/dockerinstaller.sh
	./scripts/dependencies.sh

create_app_bonus:
	./scripts/createApp.sh

expose:
	./scripts/expose.sh

setup_helm:
	./scripts/setupHelm.sh

install_gitlab:
	./scripts/installGitlab.sh