all:
	./scripts/setup.sh

re: clean
	./scripts/setup.sh

clean:
	./scripts/reset.sh

details:
	./scripts/details.sh

install:
	./scripts/dockerinstaller.sh
	./scripts/dependencies.sh

create_app:
	./scripts/createApp.sh